### ISSUE TITLE
Невозможно отписаться от стаканов с разными глубинами

### ISSUE THREAD

**Issue by falkolab** [RussianInvestments/invest-api-go-sdk#2]
У вас можно подписаться на стаканы разной глубины, но при отписке глубину нельзя указать, в итоге я не могу отписаться

https://github.com/RussianInvestments/invest-api-go-sdk/blob/22bff79c06de1323b0496b728ce0d9f2796843d3/investgo/md_stream.go#L101-L110

**Comment by jstalex** [comment]
Здравствуйте! В версии 1.4.7 исправили @falkolab
