### ISSUE TITLE
Клиент поломан (v1.24.0)

### ISSUE THREAD

**Issue by vlanse** [RussianInvestments/invest-api-go-sdk#22]
Для некоторых вызовов (напр `Shares` с параметром `InstrumentStatus_INSTRUMENT_STATUS_ALL`), где отдается большой объем данных в результате, штатное использование клиента невозможно, поскольку нельзя "нормальным" образом указать этот самый предельный размер ответа (`grpc.MaxCallRecvMsgSize`)

Костыль для обхода заключается в том, чтобы создать соединение самостоятельно и с помощью него напрямую использовать сгенеренный код, указав соответствующую опцию

P.S. Если честно, наличие корявых оберток вокруг сгенеренных вызовов в любом случае плохо объяснимо, например в текущем клиенте не удается нормально переиспользовать клиента и пробрасывать контекст для каждого вызова - контекст зачем-то закапывается внутрь клиента при создании. Т.о. если хочешь передавать правильный контекст каждый раз, надо пересоздавать клиента (и соединение). Либо же создать его один раз, и переиспользовать - но забыть про правильный контекст.

**Comment by jstalex** [comment]
Здравствуйте! Такой [вариант](https://github.com/RussianInvestments/invest-api-go-sdk/pull/23) должен решить проблему

**Comment by vlanse** [comment]
А можно еще контекст пробрасывать нормально в каждый вызов? Чтобы спокойно переиспользовать соединение, установленное однажды

Могу в принципе отдельный баг завести

**Comment by jstalex** [comment]
Добавление контекста в каждый метод это конечно хорошо, но это потребует больших изменений и сломает обратную совместимость, сейчас особо нет возможности этим заниматься(

**Comment by vlanse** [comment]
Могу предложить вариант, как сделать "сбоку", ничего не ломая. Кмк достаточно просто добавить метод, который вернет реализацию `grpc.ClientConnInterface` со всеми нужными добавками, а дальше можно использовать напрямую сгенерированные биндинги

```go
conn := // тут позвать некий новый метод, который вернет правильно подготовленное соединение
cli := investapi.NewInstrumentsServiceClient(conn)
resp, sharesErr := cli.Shares(ctx, &investapi.InstrumentsRequest{
	InstrumentStatus: lo.ToPtr(investapi.InstrumentStatus_INSTRUMENT_STATUS_ALL),
}, grpc.MaxCallRecvMsgSize(9_999_999))
```

 сейчас, чтобы обойти исходную проблему, я примерно так и сделал, однако это костыль, поскольку инициализацию соединения я целиком не копипастил, а оставил самой тривиальной , установив, по сути, только креды
```go
conn, err := grpc.NewClient(cfg.Host,
		grpc.WithTransportCredentials(credentials.NewTLS(&tls.Config{})),
		grpc.WithPerRPCCredentials(oauth.TokenSource{
			TokenSource: oauth2.StaticTokenSource(&oauth2.Token{AccessToken: cfg.Token}),
		}),
	)
```

**Comment by vlanse** [comment]
Понял-принял, попробую

**Comment by vlanse** [comment]
@jstalex прошу к просмотру https://github.com/RussianInvestments/invest-api-go-sdk/pull/24
