### ISSUE TITLE
Невозможно передать парметры TrailingStop ордера

### ISSUE THREAD

**Issue by Qwerty10291** [RussianInvestments/invest-api-go-sdk#9]
Невозможно передать парметры TrailingStop ордера в StopOrdersServiceClient.PostStopOrder). Метод принимает ссылку структуру, в которой отсутствует поле с необходимым параметром, хотя в сгенерированных proto файлах такой параметр есть

**Comment by jstalex** [comment]
Здравствуйте!
В v1.8.1 исправили
